# Generated by Django 4.2.7 on 2023-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("confirmPassword", models.CharField(max_length=100)),
            ],
        ),
    ]
