# Generated by Django 4.2.7 on 2023-11-28 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="name",
            new_name="username",
        ),
    ]
