# Generated by Django 4.2.7 on 2023-11-28 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_rename_name_register_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Register",
            new_name="User",
        ),
    ]
