# Generated by Django 4.2.7 on 2023-12-01 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_rename_register_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
